title: "[Idea] "
body:
  - type: markdown
    attributes:
      value: "Votez avec 👍 pour prioriser. / Upvote with 👍 to prioritize."
  - type: dropdown
    id: area
    attributes:
      label: "Zone / Area"
      options: ["web", "bot"]
      description: "Où s'applique l'idée ? / Where does the idea apply?"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: "Contexte / problème / Context / problem"
      placeholder: |
        FR:
        Quel problème utilisateur veut-on résoudre ?
        EN:
        What user problem do we want to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Idée de solution / Proposed solution"
      placeholder: |
        FR:
        En tant que <rôle>, je veux <action> afin de <valeur>
        EN:
        As a <role>, I want <action> so that <value>
    validations:
      required: true
  - type: textarea
    id: impacts
    attributes:
      label: "Impact / alternatives / Impact / alternatives"
      placeholder: |
        FR:
        Alternatives, risques, mesure de succès
        EN:
        Alternatives, risks, measure of success
