title: "[Q] "
body:
  - type: dropdown
    id: area
    attributes:
      label: "Zone / Area"
      options: ["web", "bot", "général"]
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: "Détail de la question / Question details"
      placeholder: |
        FR:
        Explique clairement le problème et ce que tu as essayé
        EN:
        Clearly explain the issue and what you have tried
    validations:
      required: true
  - type: textarea
    id: refs
    attributes:
      label: "Liens / captures (facultatif) / Links / screenshots (optional)"
